version: "3"
services:

  redis:
    image: 'bitnami/redis:latest'
    volumes:
      - redis:/var/lib/redis/data/
    restart: 'always'
    env_file:
    # Changed from _database.env to match likely existing setup if needed, but keeping consistently
      - _database.env
    networks:
      - nearvendor-backend

  db:
    image: 'postgis/postgis'
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: 'always'
    env_file:
      - _database.env
    networks:
      - nearvendor-backend

  backend:
    build:
      context: .
    image: nearvendor-backend:latest
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - .env:/app/.env
    ports:
      - '3836:3836'
    networks:
      - nearvendor-backend

networks:
  nearvendor-backend:
volumes:
  postgres-data:
  redis:
