# renew_before_expiry = 30 days
version = 2.10.0
archive_dir = /etc/letsencrypt/archive/noxyra-ai.com
cert = /etc/letsencrypt/live/noxyra-ai.com/cert.pem
privkey = /etc/letsencrypt/live/noxyra-ai.com/privkey.pem
chain = /etc/letsencrypt/live/noxyra-ai.com/chain.pem
fullchain = /etc/letsencrypt/live/noxyra-ai.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 8e84a3e8dd7aab75e27f568a31264fa0
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
noxyra-ai.com = /var/www/certbot
