server {
    listen 80;
    server_name noxyra-ai.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name noxyra-ai.com;

    ssl_certificate /etc/letsencrypt/live/noxyra-ai.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/noxyra-ai.com/privkey.pem;

    location / {
        root /var/www/noxyra;
        index index.html;
        try_files $uri $uri/ =404;
    }
}