server {
    listen 80;
    server_name noxyra-ai.com;

    # Needed for Certbot challenges
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        root /var/www/noxyra;
        index index.html;
        try_files $uri $uri/ =404;
    }
}